name: "godot-ci export"
on: 
  push: 
    branches: 
      - "main"

env:
  GODOT_VERSION: 4.2.1
  EXPORT_NAME: TrollDOOM
  # Set up these as Github Secrets:
  # ITCHIO_API_KEY
  # ITCHIO_USERNAME
  # ITCHIO_GAME

jobs:
  deploy-web:
    name: Godot Export
    runs-on: ubuntu-20.04
    container:
      image: docker://barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with: 
          lfs: 'true'
        
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable

      - name: Web Build
        run: |
            mkdir -v -p build/web
            godot --headless -v --export-release "Web" build/web/index.html

      - name: Mac Build
        run: |
          mkdir -v -p build/mac
          godot --headless --verbose --export-release "Mac OSX" build/mac/$EXPORT_NAME.zip

      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          godot --headless --verbose --export-release "Windows Desktop" build/windows/$EXPORT_NAME.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Web
          path: ./build/web/

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Windows
          path: ./build/windows/

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: MacOS
          path: ./build/mac/

  
      - name: Itch.io
        env: 
          BUTLER_API_KEY: ${{ secrets.ITCHIO_API_KEY }}
        run: butler push ./build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAME }}:web